name: release

on:
  release:
    types: [created]
  pull_request:
    branches: [ master ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build
      run: |
        python setup.py sdist bdist_wheel --universal
    - name: Install from Test PyPI and check
      run: |
        python -m pip install --upgrade pip
        mkdir tmp && cd tmp
        pip install easypyplot
        python -c "import easypyplot; import sys; sys.stdout.write(easypyplot.__version__ + '\n')"

